# Run the following command from Sea-Level-Indicators to install all necessary packages
# in a conda environment called sli-pipeline

# conda env create -f SLI-pipeline/src/tools/package.yaml -n sli-pipeline

name: sli-pipeline

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.7.7
  - pyresample=1.20.0
  - numpy=1.20.2
  - pyyaml=5.4.1
  - netcdf4=1.5.6
  - python-dateutil=2.8.1
  - requests=2.25.1
  - xarray=0.16.2
  - webdavclient3=3.14.5
  - matplotlib=3.3.4
  - h5py=3.2.1
