# =====================================================
# Indicators
# =====================================================

# Define which method of index calculation to use
method: 3

# Define which along track combination to use
# Use the desired combination name below (combination_s in solr regridded_cycle entries)
combination: COMBINATION_1

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
