# =====================================================
# Dataset
# =====================================================
ds_name: "MEASURES_1812" # Name for dataset
version: 1.2
cycle_length: 5
data_type: gridded

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
