# =====================================================
# Processing
# =====================================================
version: 1.0

# =====================================================
# Along Track
# =====================================================
# Here, you can dictate which instruments will be combined
# into a single along track cycle.

# Can use keywords:
#   - 'EARLIEST' - start at earliest cycle in Solr
#   - 'NOW' - current date

# ex:
#   - name: 'COMBINATION_1'
#     CRYOSAT_2: ['EARLIEST', '2015-12-31']
#     JASON_3: ['2016-01-01', 'NOW']
#   - name: 'COMBINATION_2'
#     SENTINEL_3A: ['2017-01-01', '2021-12-31']
#     SENTINEL_3B: ['2017-01-01', '2021-12-31']


combinations:
  # - name: 'CRYOSAT_2'
  #   CRYOSAT_2: ['EARLIEST', 'NOW']
  # - name: 'ENVISAT_1'
  #   ENVISAT_1: ['EARLIEST', 'NOW']
  # - name: 'ERS_1'
  #   ERS_1: ['EARLIEST', 'NOW']
  # - name: 'ERS_2'
  #   ERS_2: ['EARLIEST', 'NOW']
  # - name: 'JASON_3'
  #   JASON_3: ['EARLIEST', 'NOW']
  # - name: 'SARAL'
  #   SARAL: ['EARLIEST', 'NOW']
  # - name: 'SENTINEL_3A'
  #   SENTINEL_3A: ['EARLIEST', 'NOW']
  # - name: 'SENTINEL_3B'
  #   SENTINEL_3B: ['EARLIEST', 'NOW']
  # - name: 'GSFC'
  #   GSFC: ['EARLIEST', 'NOW']
  - name: 'COMBINATION_1'
    ERS_1: ['EARLIEST', '1995-04-25']
    ERS_2: ['EARLIEST', '2002-05-14']
    ENVISAT_1: ['EARLIEST', '2012-01-01']
    CRYOSAT_2: ['2012-01-01', '2013-03-14']
    SARAL: ['EARLIEST', '2016-07-04']
    SENTINEL_3A: ['EARLIEST', '2018-05-08']
    SENTINEL_3B: ['EARLIEST', 'NOW']



# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
