# =====================================================
# Processing
# =====================================================
version: 1.0

# =====================================================
# Along Track
# =====================================================
# Here, you can dictate which instruments will be combined
# into a single along track cycle.
# ex:
#   - name: 'COMBINATION_1'
#     CRYOSAT_2: ['2017-01-01', '2021-12-31']
#     JASON_3: ['2017-01-01', '2021-12-31']
#   - name: 'COMBINATION_2'
#     SENTINEL_3A: ['2017-01-01', '2021-12-31']
#     SENTINEL_3B: ['2017-01-01', '2021-12-31']


combinations:
  - name: 'CRYOSAT_2'
    CRYOSAT_2: ['2017-01-01', 'NOW']



# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
