# =====================================================
# Processing
# =====================================================
version: 1.0

# =====================================================
# Along Track
# =====================================================
# Here, you can dictate which instruments will be combined
# into a single along track cycle.

# Can use keywords:
#   - 'EARLIEST' - start at earliest cycle in Solr
#   - 'NOW' - current date

# ex:
#   - name: 'COMBINATION_1'
#     CRYOSAT_2: ['EARLIEST', '2015-12-31']
#     JASON_3: ['2016-01-01', 'NOW']
#   - name: 'COMBINATION_2'
#     SENTINEL_3A: ['2017-01-01', '2021-12-31']
#     SENTINEL_3B: ['2017-01-01', '2021-12-31']


combinations:
  # DAILY is a required combination. MEASURES_1812 is automatically performed.

  - name: 'DAILY'
    times: ['2019-01-01', 'NOW']
    instruments: [JASON_3_again, SENTINEL_3B]
    # JASON_3_again: ['2019-01-01', 'NOW']
    # SENTINEL_3B: ['2019-01-01', 'NOW']


  # COMPLETE ALONG TRACK DAILY COMBINATION
  # - name: 'COMBINATION_1'
  #   ERS_1: ['1992-09-25', '1995-04-24']
  #   ERS_2: ['1995-04-25', '2002-05-23']
  #   ENVISAT_1: ['2002-05-24', '2011-12-31']
  #   CRYOSAT_2: ['2012-01-01', '2013-03-14']
  #   SARAL: ['2013-03-15', '2016-07-03']
  #   SENTINEL_3A: ['2016-07-04', '2018-06-28']
  #   SENTINEL_3B: ['2018-06-29', 'NOW']


  # INDIVIDUAL ALONG TRACK DAILY DATASETS
  # - name: 'CRYOSAT_2'
  #   CRYOSAT_2: ['EARLIEST', 'NOW']
  # - name: 'ENVISAT_1'
  #   ENVISAT_1: ['EARLIEST', 'NOW']
  # - name: 'ERS_1'
  #   ERS_1: ['EARLIEST', 'NOW']
  # - name: 'ERS_2'
  #   ERS_2: ['EARLIEST', 'NOW']
  # - name: 'JASON_3'
  #   JASON_3: ['EARLIEST', 'NOW']
  # - name: 'SARAL'
  #   SARAL: ['EARLIEST', 'NOW']
  # - name: 'SENTINEL_3A'
  #   SENTINEL_3A: ['EARLIEST', 'NOW']
  # - name: 'SENTINEL_3B'
  #   SENTINEL_3B: ['EARLIEST', 'NOW']
  # - name: 'GSFC'
  #   GSFC: ['EARLIEST', 'NOW']
  # - name: 'JASON_3_again'
  #   JASON_3_again: ['EARLIEST', 'NOW']



# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
