# =====================================================
# Processing
# =====================================================
version: 1.0

# =====================================================
# Along Track
# =====================================================
# Here, you can dictate which instruments will be combined
# into a single along track cycle.

jason_3_date_range: ["1992-01-01", "2020-12-31"]
sentinel_date_range: ["1992-01-01", "2020-12-31"]

# =====================================================
# Solr
# =====================================================
solr_host_local: http://localhost:8983/solr/ # doesn't change if following standard Solr setup
solr_collection_name: sealevel_datasets # doesn't change
